# Generated by Django 2.0.7 on 2018-07-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('section_type', models.CharField(choices=[('BLOB', 'Blob'), ('LIST', 'List')], default='BLOB', max_length=4)),
                ('content', models.TextField()),
                ('sidebar', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
