# Generated by Django 2.0.7 on 2018-07-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='tagline',
            field=models.CharField(default='', max_length=280),
        ),
    ]
