# Generated by Django 2.0.7 on 2018-07-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_section_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('BLOB', 'Blob'), ('LIST', 'List'), ('GRID', 'Grid')], default='BLOB', max_length=4),
        ),
    ]
