# Generated by Django 2.0.7 on 2018-07-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_section_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
