# Generated by Django 2.0.7 on 2018-07-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180721_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='background_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='listitem',
            name='style',
            field=models.TextField(blank=True),
        ),
    ]
