# Generated by Django 2.0.7 on 2018-07-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180721_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='slug',
            field=models.SlugField(default='temp'),
            preserve_default=False,
        ),
    ]
